main:
  build: .
  dockerfile: Dockerfile.main
  environment:
    - MINE_NAME=${MINE_NAME}
    - DB_USER=${MINE_NAME}
    - DB_PWD=intermine0312
    - DB_MAIN=${MINE_NAME}
    - DB_ITEMS=${MINE_NAME}-items
    - DB_PROFILE=${MINE_NAME}-userprofile
  volumes:
    - "${DATA_DIR}:/data"
    - "${INTERMINE_DIR}:/intermine"
  links:
    - postgres
    - tomcat
tomcat:
  build: .
  dockerfile: Dockerfile.tomcat
  #environment:
  #  - TOMCAT_USER=tomcat
  #  - TOMCAT_PWD=tomcat0312
  ports:
    - "8080:8080"
  links:
    - postgres
postgres:
  image: postgres
