webapp:
  build: .
  dockerfile: Dockerfile.webapp
  ports:
   - "8888:8888"
  environment:
   - MINE_NAME=$MINE_NAME
   - PSQL_USER=intermine
   - PSQL_PWD=intermine0312
   - PSQL_DB=intermine
   - PSQL_DB_ITEMS=intermine-items
   - PSQL_DB_USER=intermine-userprofile
   - TOMCAT_USER=tomcat
   - TOMCAT_PWD=tomcat0312
   - TOMCAT_PORT=8888
  volumes_from:
   - data
  links:
   - postgres
data:
  image: centos:centos7
  volumes:
    - "$DATA_DIR:/data"
    - "$INTERMINE_DIR:/intermine"
  entrypoint: ["tail", "-f", "/dev/null"]
postgres:
  image: postgres
